'''
MODIFIQUE AS FUNÇÕES QUE FORAM CRIADAS NO DESAFIO 107 PARA QUE ELAS ACEITEM UM PARÂMETRO A MAIS, INFORMANDO SE O VALOR
RETORNADO POR ELAS VAI SER OU NÃO FORMADO PELA FUNÇÃO MOEDA(), DESENVOLVIDA NO DESAFIO 108.
'''

# EXERCÍCIO RESOLVIDO ESTÁ DENTRO DA PASTA EX109