'''
ADAPTE O CÓDIGO DO DESAFIO 107, CRIANDO UMA FUNÇÃO ADICIONAL CHAMADA MOEDA() QUE CONSIGA MOSTRAR OS VALORES COMO UM VALOR
MONETÁRIO FORMATADO.
'''

# EXERCÍCIO RESOLVIDO ESTÁ DENTRO DA PASTA EX108