'''
DENTRO DO PACOTE UTILIDADESCEV QUE CRIAMOS NO DESAFIO 111, TEMOS UM MÓDULO CHAMADO DADO. CRIE UMA FUNÇÃO CHAMADA
LEIADINHEIRO() QUE SEJA CAPAZ DE FUNCIONAR COMO A FUNÇÃO INPUT(), MAS COM UMA VALIDAÇÃO DE DADOS PARA ACEITAR APENAS VALORES
QUE SEJAM MOETÁRIOS.
'''


# EXERCÍCIO RESOLVIDO ESTÁ DENTRO DA PASTA EX112