'''
ADICIONA AO MÓDULO MOEDA.PY CRIADO NOS DESAFIOS ANTERIORES, UMA FUNÇÃO CHAMADA RESUMO(), QUE MOSTRE NA TELA ALGUMAS
INFORMAÇÕES GERADAS PELAS FUNÇÕES QUE JÁ TEMOS NO MÓDULO CRIADO ATÉ AQUI.
'''


# EXERCÍCIO RESOLVIDO ESTÁ DENTRO DA PASTA EX110