'''
CRIE UM PACOTE CHAMADO UTILIDADECEV QUE TEMHA DOIS MÓDULOS INTERNOS CHAMADOS MOEDA E DADO.
TRANSFIRA TODAS AS FUNÇÕES UTILIZADAS NOS DESAFIOS 107, 108 E 109 PARA O PRIMEIRO PACOTE E MANTENHA TUDO FUNCIONANDO.
'''

# EXERCÍCIO RESOLVIDO ESTÁ DENTRO DA PASTA EX111